'use strict';

module.exports = {
   menu: document.querySelector('.menu'),
   lobby: document.querySelector('.lobby'),
   loading: document.querySelector('.loading'),
   connectionText: document.querySelector('.connection-text'),
   createButton: document.querySelector('.create'),
   createRoomButton: document.querySelector('.create-room'),
   createMenu: document.querySelector('.create-menu'),
   menuMain: document.querySelector('.menu .main'),
   privateCheckBox: document.querySelector('#private-checkbox'),
   passwordSection: document.querySelector('.server-password'),
   roomDiv: document.querySelector('.rooms'),
   usernameOverlay: document.getElementById('username-overlay'),
   privateOverlay: document.getElementById('password-overlay'),
   usernameInput: document.querySelector('.username-input'),
   passwordInput: document.querySelector('.password-input'),
   chat: document.querySelector('.chat'),
   // privateEnterButton: document.querySelector('#password-enter-button'),
   // usernameEnterButton: document.querySelector('#username-enter-button'),
   createBackButton: document.querySelector('#create-back-button'),
   serverNameInput: document.querySelector('.server-name-input'),
   serverDescInput: document.querySelector('.server-desc-input'),
   serverUsernameInput: document.querySelector('.server-username-input'),
   serverPasswordInput: document.querySelector('.server-password-input'),
   chatInput: document.querySelector('.chat-input'),
   playerCount: document.querySelector('.player-count'),
   chatMessages: document.querySelector('.chat-messages'),
   leaveButton: document.querySelector('.leave'),
   roomTitle: document.querySelector('.room-title'),
   readyCounter: document.querySelector('.ready-counter'),
   readyButton: document.querySelector('.ready'),
   game: document.querySelector('.game'),
   canvas: document.querySelector('.game-canvas'),
   gui: document.querySelector('.gui'),
   forfeitButton: document.querySelector('.forfeit'),
};
